version: 2.1

jobs:
  build:
    working_directory: ~/go-lang
    docker:
      - image: circleci/golang:1.15.8
    steps:
        - run:
            name: Run tests
            command: make run-tests
              mkdir -p /tmp/test-reports
              gotestsum --junitfile /tmp/test-reports/unit-tests.xml

workflows:
  build: 
    jobs:
      - build

