version: 2.1

jobs:
  build:
    working_directory: ~/go-lang
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
        - run:
            name: Run tests
            command: make run-tests
              mkdir -p /tmp/test-reports
              gotestsum --junitfile /tmp/test-reports/unit-tests.xml
        - store_test_results:
            path: /tmp/test-reports

workflows:
  build: 
    jobs:
      - build

