version: 2.1

jobs:
  build:
    working_directory: ~/go-lang
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -v ./...

workflows:
  test and run :
    jobs:
      - build
